// This file is auto-generated by AutoUIBindEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class LevelChoiceItem
    {
        #region Buttons
        [SerializeField] private CustomButton ClickAreaBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI LevelTxt;
        #endregion

        #region Images
        [SerializeField] private Image PassedImg;
        [SerializeField] private Image AdImg;
        [SerializeField] private Image LockImg;
        #endregion
    }
