// This file is auto-generated by AutoUIBindEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class LevelChoiceItem
    {
        #region Buttons
        [SerializeField] private CustomButton ClickAreaBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI LevelTxt;
        #endregion

    }
