// This file is auto-generated by AutoUIBindEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GameSettingContent
    {
        #region Toggles
        [SerializeField] private Toggle MusicToggle;
        [SerializeField] private Toggle SfxToggle;
        [SerializeField] private Toggle VibrationToggle;
        #endregion
    }
