// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class PasswordPopup
    {
        #region Buttons
        [SerializeField] private CustomButton Input1Btn;
        [SerializeField] private CustomButton Input2Btn;
        [SerializeField] private CustomButton Input3Btn;
        [SerializeField] private CustomButton Input4Btn;
        [SerializeField] private CustomButton Input5Btn;
        [SerializeField] private CustomButton Input6Btn;
        [SerializeField] private CustomButton Input7Btn;
        [SerializeField] private CustomButton Input8Btn;
        [SerializeField] private CustomButton Input9Btn;
        [SerializeField] private CustomButton CloseBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI Num1Txt;
        [SerializeField] private TextMeshProUGUI Num2Txt;
        [SerializeField] private TextMeshProUGUI Num3Txt;
        [SerializeField] private TextMeshProUGUI Num4Txt;
        #endregion

    }
