
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Config.Level
{ 
    public enum GameType
    {
        /// <summary>
        /// 普通关卡
        /// </summary>
        Default = 0,
    }

} 

