
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Config.Level
{ 
    public enum LevelLockType
    {
        /// <summary>
        /// 不上锁关卡
        /// </summary>
        Unlock = 0,
        /// <summary>
        /// 广告上锁关卡
        /// </summary>
        Ad = 1,
    }

} 

