
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config
{
public sealed partial class LevelData : Luban.BeanBase
{
    public LevelData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["levelType"].IsNumber) { throw new SerializationException(); }  LevelType = (Level.GameType)_buf["levelType"].AsInt; }
        { if(!_buf["lockType"].IsNumber) { throw new SerializationException(); }  LockType = (Level.LevelLockType)_buf["lockType"].AsInt; }
    }

    public static LevelData DeserializeLevelData(JSONNode _buf)
    {
        return new LevelData(_buf);
    }

    /// <summary>
    /// uniqueID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡索引
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 关卡类型
    /// </summary>
    public readonly Level.GameType LevelType;
    /// <summary>
    /// 锁定方式
    /// </summary>
    public readonly Level.LevelLockType LockType;
   
    public const int __ID__ = 347258158;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "level:" + Level + ","
        + "levelType:" + LevelType + ","
        + "lockType:" + LockType + ","
        + "}";
    }
}
}

