
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Config
{
public partial class Tables
{
    public LubanConfig.TbGlobalConst TbGlobalConst {get; }
    public TbLevelConfig TbLevelConfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGlobalConst = new LubanConfig.TbGlobalConst(loader("lubanconfig_tbglobalconst"));
        TbLevelConfig = new TbLevelConfig(loader("tblevelconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGlobalConst.ResolveRef(this);
        TbLevelConfig.ResolveRef(this);
    }
}

}
