
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Config.LubanConfig
{
public partial class TbGlobalConst
{
    private readonly System.Collections.Generic.Dictionary<int, LubanConfig.GlobalConst> _dataMap;
    private readonly System.Collections.Generic.List<LubanConfig.GlobalConst> _dataList;
    
    public TbGlobalConst(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, LubanConfig.GlobalConst>(count);
        _dataList = new System.Collections.Generic.List<LubanConfig.GlobalConst>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LubanConfig.GlobalConst _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Config.LubanConfig.GlobalConst.DeserializeGlobalConst(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.X1, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LubanConfig.GlobalConst> DataMap => _dataMap;
    public System.Collections.Generic.List<LubanConfig.GlobalConst> DataList => _dataList;

    public LubanConfig.GlobalConst GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LubanConfig.GlobalConst Get(int key) => _dataMap[key];
    public LubanConfig.GlobalConst this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

