// This file is auto-generated by BaseUIViewEditor
// Do not modify this file manually

using UnityEngine;
using UnityEngine.UI;
using TMPro;

    public partial class GamePlayPanel
    {
        #region Buttons
        [SerializeField] private CustomButton LeftMoveBtn;
        [SerializeField] private CustomButton RightMoveBtn;
        [SerializeField] private CustomButton JumpBtn;
        [SerializeField] private CustomButton ResetBtn;
        [SerializeField] private CustomButton PauseBtn;
        [SerializeField] private CustomButton TipsBtn;
        #endregion

        #region Texts
        [SerializeField] private TextMeshProUGUI LevelTxt;
        #endregion

    }
